spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3307/bmzs?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
      username: root
      password: Cg666666

  jpa:
      database: mysql
      show-sql: true
      generate-ddl: false
#      hibernate:
#        ddl-auto: update
  flyway:
    enabled: true
    locations: classpath:db/migration,classpath:db/migration-testdata
