CREATE TABLE `required_item` (
  `required_item_id` int(11) NOT NULL AUTO_INCREMENT,
  `name` tinyint(1) NOT NULL DEFAULT '0' COMMENT '用户姓名',
  `sex` tinyint(1) DEFAULT '0' COMMENT '用户性别, 0表示男 1表示女',
  `age` tinyint(1) DEFAULT '0' COMMENT '用户年龄',
  `address` tinyint(1) DEFAULT '0' COMMENT '用户地址',
  `phone` tinyint(1) DEFAULT '0' COMMENT '用户手机号',
  `wechat_number` tinyint(1) DEFAULT '0' COMMENT '用户微信号',
  `qq_number` tinyint(1) DEFAULT '0' COMMENT '用户qq号',
  `email` tinyint(1) DEFAULT '0' COMMENT '用户邮箱',
  `school` tinyint(1) DEFAULT '0' COMMENT '用户学校',
  `grade` tinyint(1) DEFAULT '0' COMMENT '用户年级',
  `class_number` tinyint(1) DEFAULT '0' COMMENT '用户班级',
  `student_id` tinyint(1) DEFAULT '0' COMMENT '用户学号',
  `work_place` tinyint(1) DEFAULT '0' COMMENT '用户工作单位',
  `department` tinyint(1) DEFAULT '0' COMMENT '用户部门',
  `position` tinyint(1) DEFAULT '0' COMMENT '用户职位',
  `job_number` tinyint(1) DEFAULT '0' COMMENT '用户工号',
  `province` tinyint(1) DEFAULT '0' COMMENT '用户省份',
  `city` tinyint(1) DEFAULT '0' COMMENT '用户城市',
  `field_one` tinyint(1) DEFAULT '0' COMMENT '自定义字段1',
  `field_two` tinyint(1) DEFAULT '0' COMMENT '自定义字段2',
  `field_three` tinyint(1) DEFAULT '0' COMMENT '自定义字段3',
  PRIMARY KEY (`required_item_id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='必填信息表'