alter table required_item modify column `sex` tinyint(1) NULL DEFAULT NULL COMMENT '用户性别, 0表示男 1表示女';
alter table required_item change `studentId` `student_id` tinyint(1) NULL DEFAULT NULL COMMENT '用户学号';
-- 删除默认值
alter table required_item alter column `name` drop default;
alter table required_item alter column `sex` drop default;
alter table required_item alter column `age` drop default;
alter table required_item alter column `address` drop default;
alter table required_item alter column `phone` drop default;
alter table required_item alter column `wechat_number` drop default;
alter table required_item alter column `qq_number` drop default;
alter table required_item alter column `email` drop default;
alter table required_item alter column `school` drop default;
alter table required_item alter column `grade` drop default;
alter table required_item alter column `class_number` drop default;
alter table required_item alter column `student_id` drop default;
alter table required_item alter column `work_place` drop default;
alter table required_item alter column `department` drop default;
alter table required_item alter column `position` drop default;
alter table required_item alter column `job_number` drop default;
alter table required_item alter column `province` drop default;
alter table required_item alter column `city` drop default;
alter table required_item alter column `field_one` drop default;
alter table required_item alter column `field_two` drop default;
alter table required_item alter column `field_three` drop default;

-- 设置默认值为0
alter table required_item alter column `name` set default 0;
alter table required_item alter column `sex` set default 0;
alter table required_item alter column `age` set default 0;
alter table required_item alter column `address` set default 0;
alter table required_item alter column `phone` set default 0;
alter table required_item alter column `wechat_number` set default 0;
alter table required_item alter column `qq_number` set default 0;
alter table required_item alter column `email` set default 0;
alter table required_item alter column `school` set default 0;
alter table required_item alter column `grade` set default 0;
alter table required_item alter column `class_number` set default 0;
alter table required_item alter column `student_id` set default 0;
alter table required_item alter column `work_place` set default 0;
alter table required_item alter column `department` set default 0;
alter table required_item alter column `position` set default 0;
alter table required_item alter column `job_number` set default 0;
alter table required_item alter column `province` set default 0;
alter table required_item alter column `city` set default 0;
alter table required_item alter column `field_one` set default 0;
alter table required_item alter column `field_two` set default 0;
alter table required_item alter column `field_three` set default 0;